# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
     
4/*This object will hold the information of an order. It will hold (1) Order ID (2) Difficulty Rating (3)
5Order Status ((i) Incomplete(ii) InProgress (iii) Complete (iv) Delivered) (4) Collection of
49	 */
50	public Order(int orderId, Vector<OrderOfDish> orderedDishes, Address customerAdress){
51		this._orderId= orderId;
86	public Vector<OrderOfDish> getDishes(){
87		Vector<OrderOfDish> orderedDishes= new Vector<OrderOfDish>();
88		int numofdishes= _orderedDishes.size();
127		for(int i=0; i < this._orderedDishes.size(); i++){